#!/bin/sh

# Set colors
xrdb ~/.Xresources

# Startup volume
pactl set-sink-volume 0 '20%' &

# Libinput gestures
libinput-gestures-setup start

# Disable beeps
xset -b &

# Keyboard layout
setxkbmap \
  -layout us,it \
  -option ctrl:nocaps \
  -option grp:alt_space_toggle \
  -option shift:both_capslock_cancel \
  -option compose:ralt \
  -option terminate:ctrl_alt_bksp &

# Fast typing
# Defaults to 660 25
xset r rate 200 30

# Set LCD brightness
xbacklight -set 90 &

# DPMS monitor setting (standby -> suspend -> off) (seconds)
xset dpms 300 600 0 &

# OSD
dunst &

# Set natural scrolling and tap to click
xinput --set-prop 11 275 1
xinput --set-prop 11 285 1

# Compton
compton --config ~/.compton.conf &
